# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: guacamole-dbpassword
  namespace: guacamole
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password  
type: Opaque
data:
  username: cG9zdGdyZXM=
---
