apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: guacamole-initdb
  namespace: guacamole
  labels:
    app: guacamole
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-db
  namespace: guacamole
  labels:
    app: guacamole
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
